ERROR - 2021-02-03 07:29:49 --> mysqli_sql_exception: Table 'todo.users' doesn't exist in /var/www/todo/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/todo/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT *\nFROM `...')
#1 /var/www/todo/vendor/codeigniter4/framework/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /var/www/todo/vendor/codeigniter4/framework/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /var/www/todo/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/todo/vendor/codeigniter4/framework/system/Model.php(169): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/todo/vendor/codeigniter4/framework/system/BaseModel.php(518): CodeIgniter\Model->doFind(true, '1')
#6 /var/www/todo/app/Controllers/User.php(36): CodeIgniter\BaseModel->find('1')
#7 /var/www/todo/vendor/codeigniter4/framework/system/CodeIgniter.php(936): App\Controllers\User->find('1')
#8 /var/www/todo/vendor/codeigniter4/framework/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#9 /var/www/todo/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/todo/public/index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-03 07:29:49 --> Table 'todo.users' doesn't exist
#0 /var/www/todo/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT *\nFROM `...')
#1 /var/www/todo/vendor/codeigniter4/framework/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /var/www/todo/vendor/codeigniter4/framework/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /var/www/todo/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/todo/vendor/codeigniter4/framework/system/Model.php(169): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/todo/vendor/codeigniter4/framework/system/BaseModel.php(518): CodeIgniter\Model->doFind(true, '1')
#6 /var/www/todo/app/Controllers/User.php(36): CodeIgniter\BaseModel->find('1')
#7 /var/www/todo/vendor/codeigniter4/framework/system/CodeIgniter.php(936): App\Controllers\User->find('1')
#8 /var/www/todo/vendor/codeigniter4/framework/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#9 /var/www/todo/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/todo/public/index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2021-02-03 07:35:35 --> mysqli_sql_exception: Table 'todo.users' doesn't exist in /var/www/todo/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/todo/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT *\nFROM `...')
#1 /var/www/todo/vendor/codeigniter4/framework/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /var/www/todo/vendor/codeigniter4/framework/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /var/www/todo/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/todo/vendor/codeigniter4/framework/system/Model.php(169): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/todo/vendor/codeigniter4/framework/system/BaseModel.php(518): CodeIgniter\Model->doFind(true, '1')
#6 /var/www/todo/app/Controllers/User.php(36): CodeIgniter\BaseModel->find('1')
#7 /var/www/todo/vendor/codeigniter4/framework/system/CodeIgniter.php(936): App\Controllers\User->find('1')
#8 /var/www/todo/vendor/codeigniter4/framework/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#9 /var/www/todo/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/todo/public/index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-02-03 07:35:35 --> Table 'todo.users' doesn't exist
#0 /var/www/todo/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT *\nFROM `...')
#1 /var/www/todo/vendor/codeigniter4/framework/system/Database/BaseConnection.php(713): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /var/www/todo/vendor/codeigniter4/framework/system/Database/BaseConnection.php(641): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /var/www/todo/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /var/www/todo/vendor/codeigniter4/framework/system/Model.php(169): CodeIgniter\Database\BaseBuilder->get()
#5 /var/www/todo/vendor/codeigniter4/framework/system/BaseModel.php(518): CodeIgniter\Model->doFind(true, '1')
#6 /var/www/todo/app/Controllers/User.php(36): CodeIgniter\BaseModel->find('1')
#7 /var/www/todo/vendor/codeigniter4/framework/system/CodeIgniter.php(936): App\Controllers\User->find('1')
#8 /var/www/todo/vendor/codeigniter4/framework/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#9 /var/www/todo/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /var/www/todo/public/index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2021-02-03 08:37:43 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
ERROR - 2021-02-03 08:40:54 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
ERROR - 2021-02-03 08:46:50 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
ERROR - 2021-02-03 08:47:54 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: Name or service not known
